### ISSUE TITLE
请问播放时是否有闪烁现象？

### ISSUE THREAD

**Issue by reaper2012** [samsha1971/rtsp2fmp4#1]
你好，demo搭建成功了，对理解h5+MSE非常有帮助，感谢感谢！就是我播放rtsp时（使用ffmpeg推文件rtsp流到easydarwin rtsp服务器），视频始终有闪烁现象（画面往回轻微跳那种），想确认一下是否原型就有这个问题，还是可能我哪里配置错了

**Comment by samsha1971** [comment]
这个demo只会为了保持视频同步往后跳帧。

- C++程序部分，rtsp只支持tcp方式，只进行了fmp4封装转发。

- 在example/index.html中，为了防止播放延迟，缓存会被清理。(包缓存堆积，一般是因为网络传输问题)

if (is_iframe(d) && packages.length >= 10) {
                  packages = []
                  console.log("Too many packets cached, clear it.")
                }

**Comment by samsha1971** [comment]
这个demo只会为了保持视频同步往后跳帧。

- C++程序部分，rtsp只支持tcp方式，只进行了fmp4封装转发。

- 在example/index.html中，为了防止播放延迟，缓存会被清理。(包缓存堆积，一般是因为网络传输问题)

if (is_iframe(d) && packages.length >= 10) {
                  packages = []
                  console.log("Too many packets cached, clear it.")
                }
