### ISSUE TITLE
fmp4_muxer.cpp里的AvcCBox里重复填充了结构？

### ISSUE THREAD

**Issue by wwlleo0730** [samsha1971/rtsp2fmp4#2]
在 generate_ftyp_moov 方法里，从h264源头sps pps填充到了AvcC里，但是我看原定义里，后面又重复写死了结构？

我自己这边用类似的代码发现的确重复了一段数据。

**Comment by wwlleo0730** [comment]
我截了个图，后面是多余的字节

![批注 2019-10-29 140545](https://user-images.githubusercontent.com/6244792/67741851-4fd47a80-fa55-11e9-9c08-397827b6b8de.jpg)

**Comment by samsha1971** [comment]
Thank you, bug fixed.
