### ISSUE TITLE
pipeline_error_decode

### ISSUE THREAD

**Issue by shiqifeng2000** [samsha1971/rtsp2fmp4#3]
![WechatIMG418](https://user-images.githubusercontent.com/9416410/87002468-41498000-c1ec-11ea-9cdb-ea2e5419ff1a.jpeg)

![4191594270411_ pic_hd](https://user-images.githubusercontent.com/9416410/87002693-bc129b00-c1ec-11ea-91f5-c822d78824ea.jpg)

搭建完毕，基于live555的小视频完美播放，但是换到有真正rtsp的网络摄像头时，发生了错误，到52帧无法播放
Deploy done, it will be perfect if we play some short videos with live555, but when we switch to the rtsp based network camera, error occurs, decode error when decoding the 52nd frame

**Comment by samsha1971** [comment]
Is this an HTML5 error?
Check the mimeCodec of example/index.html.

Line 132 outputs the mimeCodec for the camera:
```
If (first_frame) {
If (d[527] == 0x67) {
MimeCodec =
'video/mp4;Codecs = "avc1. '+
D [528]. ToString (16) +
D [529]. ToString (16) +
D [530]. ToString (16) +
'"'
The console. The log (" Video actual codec: '" + mimeCodec + "' ")
}
First_frame = false
}
```

Try modifying the codecs on line 32 with the mimeCodec output on line 132:
`Var mimeCodec = 'video/mp4;Codecs = "avc1.4 D002A" '`
