### ISSUE TITLE
Is it support HEVC？

### ISSUE THREAD

**Issue by myseemylife** [samsha1971/rtsp2fmp4#4]
well，hevc fmp4 videos can be played when using MSE  by chromium x64.
i did't see any hevc stuff in muxer code.Plz help

**Comment by samsha1971** [comment]
HEVC is not supported, refer to line 322 of live555.cpp.

if (strcmp(fSubsession.mediumName(), "video") == 0 &&
		(strcmp(fSubsession.codecName(), "H264") == 0))_

**Comment by myseemylife** [comment]
Thx for replying，just closed it，I‘m done’
